name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
          docker build . --file Dockerfile --tag wesaleldsokey/iti:v20
          docker login -u ${{ secrets.DOKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push wesaleldsokey/iti:v20
